'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import FilterState from "./context/filterState";
import { useRouter } from "next/navigation";
import { getCookie, hasCookie, setCookie } from 'cookies-next';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "CareerCanvas",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router  = useRouter();
  
  const languages =  {
    English : '/auto/en',
    Assamese : '/auto/as',
    Bengali : '/auto/bn',
    Gujarati : '/auto/gu',
    Hindi : '/auto/hi',
    Kannada : '/auto/kn',
    Konkani : '/auto/kok',
    Malayalam : '/auto/ml',
    Marathi : '/auto/mr',
    Nepali : '/auto/ne',
    Oriya : '/auto/or',
    Punjabi : '/auto/pa',
    Sanskrit : '/auto/sa',
    Sindhi : '/auto/sd',
    Tamil : '/auto/ta',
    Telugu : '/auto/te',
    Urdu : '/auto/ur',
    Maithili : '/auto/mai',
    Dogri : '/auto/doi'
  }

    // console.log(languages['English']);
 
    const langChange = (lang) => {
      console.log("done");
      // if (hasCookie('googtrans')) {
          setCookie('googtrans', languages[lang]);
          // setSelected(e)
      // }
      window.location.reload()
  }

  useEffect(() => {
    if (typeof window !== 'undefined') {
      import('@alan-ai/alan-sdk-web').then(({ default: alanBtn }) => {
        alanBtn({
          key: 'b71b2e5cb15cf5bcd70552aeca9033062e956eca572e1d8b807a3e2338fdd0dc/stage',
          onCommand:({command, final, lang})=>{
            if(command==='navigateToDiscussion'){
              router.push('/discussion')
            }
            else if(command==='navigateToDashboard'){
              router.push('/dashboard')
            }
            else if(command==='navigateToHome'){
              router.push('/')
            }
            else if(command==='goBack'){
              router.back();
            }
            else if(command==='goToRoadmap'){
              router.push(`/roadmap/${final}`);
            }
            else if(command==='changeLanguage'){
              console.log('done');
              langChange(lang);
            }
          }
        });

      });
    }

  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
      
          <FilterState>
            {children}
          </FilterState>
       
      </body>
    </html>
  );
}
